
---
title: "Computational Two-Dimensional Infrared Spectroscopy without Maps:<i>N</i>-Methylacetamide in Water"
doi: "10.1021/jp5011692"
date: "2014-03-31 18:49:16"
date-format: iso
authors: "Cazade, Bereau, Meuwly"
description: "_J. Phys. Chem. B_ **118** (2014)"
year: 2014
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1021/jp5011692"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

The two-dimensional infrared spectrum of NMAH and NMAD in H2O and D2O is computed on the basis of force field parametrizations ranging from standard point charge (PC) to more elaborate multipolar (MTP) representations of the electrostatics. For the latter, the nonbonded parameters (MTP and van der Waals) were optimized to reproduce thermodynamic data. The frequency trajectory and frequency-frequency correlation function (FFCF) are determined from explicit frequency calculations on ∼10(6) snapshots without using a more traditional "mapping" approach. This allows us to both sample configurations and compute observables in a consistent fashion. In agreement with experiment, the FFCF shows one very rapid time scale (in the 50 fs range) followed by one or two longer time scales. In the case of three time scales, the intermediate one is ≈0.5 ps or shorter, whereas the longest time scale can extend up to 2 or 3 ps. All interaction models lead to three time scales in the FFCF when fitted to an empirical parametrized form. When two time scales are assumed-as is usually done in the analysis of experimental data-and the short time scale is fixed to the τ1 = 50-100 fs range, the correlation time τc from the simulations ranges from 0.7 to 1 ps, which agrees quite well with experimentally determined values. The major difference between MTP and PC models is the observation that the later decay times in the FFCF are longer for simulations with MTPs. Also, the amplitude of the FFCF is reduced when simulations are carried out with MTPs. Overall, however, PC-based models perform well compared to those based on MTPs for NMAD in D2O and can be recommended for such investigations in the context of peptide and protein simulations.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">OpenAlex</cite>
</footer>
```

## TL;DR

PC-based models perform well compared to those based on MTPs for NMAD in D2O and can be recommended for such investigations in the context of peptide and protein simulations.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Cazade_2014, title={Computational Two-Dimensional Infrared Spectroscopy without Maps:<i>N</i>-Methylacetamide in Water}, volume={118}, ISSN={1520-5207}, url={http://dx.doi.org/10.1021/jp5011692}, DOI={10.1021/jp5011692}, number={28}, journal={The Journal of Physical Chemistry B}, publisher={American Chemical Society (ACS)}, author={Cazade, Pierre-André and Bereau, Tristan and Meuwly, Markus}, year={2014}, month=Apr, pages={8135–8147} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
