
---
title: "Fokker–Planck Score Learning: Efficient Free-Energy Estimation under Periodic Boundary Conditions"
doi: "10.1021/acs.jpcb.5c04579"
date: "2025-10-30 17:30:28"
date-format: iso
authors: "Nagel, Bereau"
description: "_J. Phys. Chem. B_ **129** (2025)"
year: 2025
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1021/acs.jpcb.5c04579"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

Accurate free-energy estimation is essential in molecular simulation, yet the periodic boundary conditions (PBC) commonly used in computer simulations have rarely been explicitly exploited. Equilibrium methods such as umbrella sampling, metadynamics, and adaptive biasing force require extensive sampling, while nonequilibrium pulling with Jarzynski's equality suffers from poor convergence due to exponential averaging. Here, we introduce a physics-informed, score-based diffusion framework: by mapping PBC simulations onto a Brownian particle in a periodic potential, we derive the Fokker-Planck steady-state score that directly encodes free-energy gradients. A neural network is trained on nonequilibrium trajectories to learn this score, providing a principled scheme to efficiently reconstruct the potential of mean force. On benchmark periodic potentials and small-molecule membrane permeation, our method is up to 1 order of magnitude more efficient than umbrella sampling.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## TL;DR

A physics-informed, score-based diffusion framework is introduced: by mapping PBC simulations onto a Brownian particle in a periodic potential, the Fokker-Planck steady-state score is derived that directly encodes free-energy gradients and is used to efficiently reconstruct the potential of mean force.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Nagel_2025, title={Fokker–Planck Score Learning: Efficient Free-Energy Estimation under Periodic Boundary Conditions}, volume={129}, ISSN={1520-5207}, url={http://dx.doi.org/10.1021/acs.jpcb.5c04579}, DOI={10.1021/acs.jpcb.5c04579}, number={45}, journal={The Journal of Physical Chemistry B}, publisher={American Chemical Society (ACS)}, author={Nagel, Daniel and Bereau, Tristan}, year={2025}, month=Oct, pages={11780–11790} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
