
---
title: "Automated Parametrization of the Coarse-Grained Martini Force Field for Small Organic Molecules"
doi: "10.1021/acs.jctc.5b00056"
date: "2015-04-28 16:06:36"
date-format: iso
authors: "Bereau, Kremer"
description: "_J. Chem. Theory Comput._ **11** (2015)"
year: 2015
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1021/acs.jctc.5b00056"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

The systematic exploration of chemical compound space holds many promises toward structure-function relationships and material design. In the context of computer simulations, progress is hampered by both the sheer number of compounds and the efforts associated with parametrizing a force field for every new molecule. A coarse-grained (CG) representation provides not only a reduced phase space but also a smaller number of compounds, due to the redundancy of CG representations mapping to the same structure. Though many CG models require the explicit force-field parametrization of a molecule with all others, others assume transferability by means of mixing rules, such as the Martini force field. To alleviate the burden associated with tedious parametrizations for each new compound, the present work aims at automating the mapping and parametrization of common small organic molecules for Martini. We test the method by analyzing the water/octanol partitioning of more than 650 neutral molecules, the hydration free energy of 354 others, and the free energies of hydration and solvation in octanol of another 69 compounds. Last, we compare with all-atom simulations the thermodynamics of insertion of four individual solute molecules in a phospholipid membrane. The protocol demonstrates the feasibility of an automated parametrization scheme for Martini and provides prospects for high-throughput simulation methodologies.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">OpenAlex</cite>
</footer>
```

## TL;DR

The present work aims at automating the mapping and parametrization of common small organic molecules for Martini, and demonstrates the feasibility of an automated parammetrization scheme forMartini and provides prospects for high-throughput simulation methodologies.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Bereau_2015, title={Automated Parametrization of the Coarse-Grained Martini Force Field for Small Organic Molecules}, volume={11}, ISSN={1549-9626}, url={http://dx.doi.org/10.1021/acs.jctc.5b00056}, DOI={10.1021/acs.jctc.5b00056}, number={6}, journal={Journal of Chemical Theory and Computation}, publisher={American Chemical Society (ACS)}, author={Bereau, Tristan and Kremer, Kurt}, year={2015}, month=May, pages={2783–2791} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
