
---
title: "An in-silico walker"
doi: "10.1016/j.cplett.2016.06.019"
date: "2016-06-11 07:58:41"
date-format: iso
authors: "Xiao, Chen, Bereau, Shi"
description: "_Chemical Physics Letters_ **659** (2016)"
year: 2016
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1016/j.cplett.2016.06.019"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

The paradox of biomimetic research is to perform bio-functionality, usually associated with sophisticated structures optimized by nature, with minimal structural complexity for the ease of fabrication. Here we show that a three-particle trimer can exhibit kinesin-like autonomous walk on a track via reactive molecular dynamics simulations. The autonomous motion is due to imbalanced transitions resulting from exothermic catalytic reactions, and the spatial asymmetry from the track. This molecular design can be realized by reproducing the particle–particle interactions in functionalized nano- or colloidal particles. Our results open up the possibility of fabricating bio-mimetic nano-systems in a minimalist approach.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">manual entry</cite>
</footer>
```

## TL;DR

It is shown that a three-particle trimer can exhibit kinesin-like autonomous walk on a track via reactive molecular dynamics simulations, which opens up the possibility of fabricating bio-mimetic nano-systems in a minimalist approach.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Xiao_2016, title={An in-silico walker}, volume={659}, ISSN={0009-2614}, url={http://dx.doi.org/10.1016/j.cplett.2016.06.019}, DOI={10.1016/j.cplett.2016.06.019}, journal={Chemical Physics Letters}, publisher={Elsevier BV}, author={Xiao, Qiran and Chen, Yanping and Bereau, Tristan and Shi, Yunfeng}, year={2016}, month=Aug, pages={6–9} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
