
---
title: "Optimized convergence for multiple histogram analysis"
doi: "10.1016/j.jcp.2009.05.011"
date: "2009-05-19 05:37:31"
date-format: iso
authors: "Bereau, Swendsen"
description: "_Journal of Computational Physics_ **228** (2009)"
year: 2009
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1016/j.jcp.2009.05.011"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

We propose a new algorithm for solving the weighted histogram analysis method (WHAM) equations to estimate free energies out of a set of Monte Carlo (MC) or molecular dynamics (MD) simulations. The algorithm, based on free-energy differences, provides a more natural way of approaching the problem and improves convergence compared to the widely used direct iteration method. We also study how parameters (temperature, pressure, etc.) of the independent simulations should be chosen to optimize the accuracy of the set of free energies.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">manual entry</cite>
</footer>
```

## TL;DR

A new algorithm for solving the weighted histogram analysis method (WHAM) equations to estimate free energies out of a set of Monte Carlo (MC) or molecular dynamics (MD) simulations, based on free-energy differences is proposed.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Bereau_2009, title={Optimized convergence for multiple histogram analysis}, volume={228}, ISSN={0021-9991}, url={http://dx.doi.org/10.1016/j.jcp.2009.05.011}, DOI={10.1016/j.jcp.2009.05.011}, number={17}, journal={Journal of Computational Physics}, publisher={Elsevier BV}, author={Bereau, Tristan and Swendsen, Robert H.}, year={2009}, month=Sept, pages={6119–6129} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
