
---
title: "Direct route to reproducing pair distribution functions with coarse-grained models via transformed atomistic cross correlations"
doi: "10.1063/1.5131105"
date: "2019-12-26 13:52:00"
date-format: iso
authors: "Wörner, Bereau, Kremer, Rudzinski"
description: "_The Journal of Chemical Physics_ **151** (2019)"
year: 2019
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1063/1.5131105"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

Coarse-grained (CG) models are often parameterized to reproduce one-dimensional structural correlation functions of an atomically detailed model along the degrees of freedom governing each interaction potential. While cross correlations between these degrees of freedom inform the optimal set of interaction parameters, the correlations generated from the higher-resolution simulations are often too complex to act as an accurate proxy for the CG correlations. Instead, the most popular methods determine the interaction parameters iteratively while assuming that individual interactions are uncorrelated. While these iterative methods have been validated for a wide range of systems, they also have disadvantages when parameterizing models for multicomponent systems or when refining previously established models to better reproduce particular structural features. In this work, we propose two distinct approaches for the direct (i.e., noniterative) parameterization of a CG model by adjusting the high-resolution cross correlations of an atomistic model in order to more accurately reflect correlations that will be generated by the resulting CG model. The derived models more accurately describe the low-order structural features of the underlying AA model while necessarily generating inherently distinct cross correlations compared with the atomically detailed reference model. We demonstrate the proposed methods for a one-site-per-molecule representation of liquid water, where pairwise interactions are incapable of reproducing the true tetrahedral solvation structure. We then investigate the precise role that distinct cross-correlation features play in determining the correct pair correlation functions, evaluating the importance of the placement of correlation features as well as the balance between features appearing in different solvation shells.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## TL;DR

Two distinct approaches for the direct parameterization of a CG model are proposed by adjusting the high-resolution cross correlations of an atomistic model in order to more accurately reflect correlations that will be generated by the resulting CG model.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{W_rner_2019, title={Direct route to reproducing pair distribution functions with coarse-grained models via transformed atomistic cross correlations}, volume={151}, ISSN={1089-7690}, url={http://dx.doi.org/10.1063/1.5131105}, DOI={10.1063/1.5131105}, number={24}, journal={The Journal of Chemical Physics}, publisher={AIP Publishing}, author={Wörner, Svenja J. and Bereau, Tristan and Kremer, Kurt and Rudzinski, Joseph F.}, year={2019}, month=Dec }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
