
---
title: "Drug–Membrane Permeability across Chemical Space"
doi: "10.1021/acscentsci.8b00718"
date: "2019-01-09 02:14:27"
date-format: iso
authors: "Menichetti, Kanekal, Bereau"
description: "_ACS Cent. Sci._ **5** (2019)"
year: 2019
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1021/acscentsci.8b00718"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

Unraveling the relation between the chemical structure of small druglike compounds and their rate of passive permeation across lipid membranes is of fundamental importance for pharmaceutical applications. The elucidation of a comprehensive structure–permeability relationship expressed in terms of a few molecular descriptors is unfortunately hampered by the overwhelming number of possible compounds. In this work, we reduce a priori the size and diversity of chemical space to solve an analogous—but smoothed out—structure–property relationship problem. This is achieved by relying on a physics-based coarse-grained model that reduces the size of chemical space, enabling a comprehensive exploration of this space with greatly reduced computational cost. We perform high-throughput coarse-grained (HTCG) simulations to derive a permeability surface in terms of two simple molecular descriptors—bulk partitioning free energy and pKa. The surface is constructed by exhaustively simulating all coarse-grained compounds that are representative of small organic molecules (ranging from 30 to 160 Da) in a high-throughput scheme. We provide results for acidic, basic, and zwitterionic compounds. Connecting back to the atomic resolution, the HTCG predictions for more than 500 000 compounds allow us to establish a clear connection between specific chemical groups and the resulting permeability coefficient, enabling for the first time an inverse design procedure. Our results have profound implications for drug synthesis: the predominance of commonly employed chemical moieties narrows down the range of permeabilities.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## TL;DR

This work reduces a priori the size and diversity of chemical space to solve an analogous—but smoothed out—structure–property relationship problem, and establishes a clear connection between specific chemical groups and the resulting permeability coefficient, enabling for the first time an inverse design procedure.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Menichetti_2019, title={Drug–Membrane Permeability across Chemical Space}, volume={5}, ISSN={2374-7951}, url={http://dx.doi.org/10.1021/acscentsci.8b00718}, DOI={10.1021/acscentsci.8b00718}, number={2}, journal={ACS Central Science}, publisher={American Chemical Society (ACS)}, author={Menichetti, Roberto and Kanekal, Kiran H. and Bereau, Tristan}, year={2019}, month=Jan, pages={290–298} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
