
---
title: "Hydration free energies from kernel-based machine learning: Compound-database bias"
doi: "10.1063/5.0012230"
date: "2020-07-01 10:45:39"
date-format: iso
authors: "Rauer, Bereau"
description: "_The Journal of Chemical Physics_ **153** (2020)"
year: 2020
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1063/5.0012230"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

We consider the prediction of a basic thermodynamic property-hydration free energies-across a large subset of the chemical space of small organic molecules. Our in silico study is based on computer simulations at the atomistic level with implicit solvent. We report on a kernel-based machine learning approach that is inspired by recent work in learning electronic properties but differs in key aspects: The representation is averaged over several conformers to account for the statistical ensemble. We also include an atomic-decomposition ansatz, which offers significant added transferability compared to molecular learning. Finally, we explore the existence of severe biases from databases of experimental compounds. By performing a combination of dimensionality reduction and cross-learning models, we show that the rate of learning depends significantly on the breadth and variety of the training dataset. Our study highlights the dangers of fitting machine-learning models to databases of a narrow chemical range.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## TL;DR

This study considers the prediction of a basic thermodynamic property-hydration free energies-across a large subset of the chemical space of small organic molecules and reports on a kernel-based machine learning approach that is inspired by recent work in learning electronic properties but differs in key aspects.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Rauer_2020, title={Hydration free energies from kernel-based machine learning: Compound-database bias}, volume={153}, ISSN={1089-7690}, url={http://dx.doi.org/10.1063/5.0012230}, DOI={10.1063/5.0012230}, number={1}, journal={The Journal of Chemical Physics}, publisher={AIP Publishing}, author={Rauer, Clemens and Bereau, Tristan}, year={2020}, month=July }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
