
---
title: "Fast Parametrization of Martini3 Models for Fragments and Small Molecules"
doi: "10.1021/acs.jctc.5c01178"
date: "2025-12-20 14:04:47"
date-format: iso
authors: "Szczuka, Pereira, Walter, Gueroult, Poulain, Bereau, Souza, Chavent"
description: "_J. Chem. Theory Comput._ **22** (2025)"
year: 2025
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1021/acs.jctc.5c01178"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

Coarse-grained molecular dynamics simulations, such as those performed with the recently parametrized Martini 3 force field, simplify molecular models and enable the study of larger systems over longer time scales. With this new implementation, Martini 3 allows more bead types and sizes, becoming more amenable to studying dynamical phenomena involving small molecules such as protein-ligand interactions and membrane permeation. However, while solutions existed to automatically model small molecules using the previous iteration of the Martini force field, there is no simple way to generate such molecules for Martini 3 yet. Here, we introduce Auto-MartiniM3, an advanced and updated version of the Auto-Martini program designed to automate the coarse-graining of small molecules to be used with the Martini 3 force field. We validated our approach by modeling 81 simple molecules from the Martini Database and comparing their structural and thermodynamic properties with those obtained from models designed by Martini experts. Additionally, we assessed the behavior of Auto-MartiniM3-generated models by calculating solute translocation and free energy across lipid bilayers. We also evaluated more complex molecules such as caffeine by testing its binding to the adenosine A2A receptor. Finally, our results from deploying Auto-MartiniM3 on a large data set of molecular fragments demonstrate that this program can become a tool of choice for fast, high-throughput creation of coarse-grained models of small molecules, offering a good balance between automation and accuracy. Auto-MartiniM3 source code is freely available at https://github.com/Martini-Force-Field-Initiative/Automartini_M3.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## TL;DR

The results from deploying Auto-MartiniM3 on a large data set of molecular fragments demonstrate that this program can become a tool of choice for fast, high-throughput creation of coarse-grained models of small molecules, offering a good balance between automation and accuracy.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Szczuka_2025, title={Fast Parametrization of Martini3 Models for Fragments and Small Molecules}, volume={22}, ISSN={1549-9626}, url={http://dx.doi.org/10.1021/acs.jctc.5c01178}, DOI={10.1021/acs.jctc.5c01178}, number={1}, journal={Journal of Chemical Theory and Computation}, publisher={American Chemical Society (ACS)}, author={Szczuka, Magdalena and Pereira, Gilberto P. and Walter, Luis J. and Gueroult, Marc and Poulain, Pierre and Bereau, Tristan and Souza, Paulo C. T. and Chavent, Matthieu}, year={2025}, month=Dec, pages={610–623} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
