
---
title: "Deriving Static Atomic Multipoles from the Electrostatic Potential"
doi: "10.1021/ci400548w"
date: "2013-12-05 12:42:36"
date-format: iso
authors: "Kramer, Bereau, Spinn, Liedl, Gedeck, Meuwly"
description: "_J. Chem. Inf. Model._ **53** (2013)"
year: 2013
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
---

```{=html}
<div class="float-end">
    <div data-badge-type='donut' class='altmetric-embed'
    data-badge-popover='left' data-doi="10.1021/ci400548w"></div>
</div>
<script type='text/javascript'
  src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<br><br><br>
```

::: {.panel-tabset}

## Abstract

The description of molecular systems using multipolar electrostatics calls for automated methods to fit the necessary parameters. In this paper, we describe an open-source software package that allows fitting atomic multipoles (MTPs) from the ab initio electrostatic potential by adequate atom typing and judicious assignment of the local axis system. By enabling the simultaneous fit of several molecules and/or conformations, the package addresses issues of parameter transferability and lack of sampling for buried atoms. We illustrate the method by studying a series of small alcohol molecules, as well as various conformations of protonated butylamine.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## TL;DR

An open-source software package that allows fitting atomic multipoles (MTPs) from the ab initio electrostatic potential by adequate atom typing and judicious assignment of the local axis system is described.
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">Semantic Scholar</cite>
</footer>
```

## BibTeX

```{bibtex}
@article{Kramer_2013, title={Deriving Static Atomic Multipoles from the Electrostatic Potential}, volume={53}, ISSN={1549-960X}, url={http://dx.doi.org/10.1021/ci400548w}, DOI={10.1021/ci400548w}, number={12}, journal={Journal of Chemical Information and Modeling}, publisher={American Chemical Society (ACS)}, author={Kramer, Christian and Bereau, Tristan and Spinn, Alexander and Liedl, Klaus R. and Gedeck, Peter and Meuwly, Markus}, year={2013}, month=Dec, pages={3410–3417} }
```
```{=html}
<footer class="blockquote-footer">from <cite title="Source Title">doi2bib</cite>
</footer>
```


:::
