"""Generate the homepage's recent-work list as a Quarto include.

The list used to be an OJS cell reading `data/all_papers.json` in the browser.
That works, but it made the landing page -- the one page that has to render --
depend on the OJS runtime, and a stalled cell leaves an empty "Recent work"
heading rather than degrading to nothing. The same five entries are now baked
into `_recent_work.md` at build time, so index.qmd carries no executable code
at all.

The trade is that the file has to be regenerated when the publication data
changes, which is why `fetch_papers.py` and `embed_papers.py` both call
`write_include` right after they write the exports. Run standalone with::

    poetry run python scripts/recent_work.py

Files beginning with an underscore are not rendered as pages by Quarto, so the
include never becomes a stray URL of its own.
"""

import html
import json
import re
import sys
from pathlib import Path

try:
    from to_quarto.utils import ROOT_DIR
except ImportError:  # invoked as `python scripts/recent_work.py` from the root
    ROOT_DIR = Path(__file__).parent.parent.absolute()

PAPERS_JSON = Path(ROOT_DIR).joinpath("data", "all_papers.json")
INCLUDE_FILE = Path(ROOT_DIR).joinpath("_recent_work.md")

N_ENTRIES = 5

# Zenodo software depositions are real outputs but read oddly as a headline,
# and each duplicates the paper it accompanies. `conference` is deliberately
# kept: Split-Flows is an AISTATS paper.
EXCLUDED_KINDS = {"repository"}

# Past this many authors the list is truncated, to keep an entry to two lines.
MAX_AUTHORS = 4
KEEP_AUTHORS = 3

HEADER = """<!-- GENERATED by scripts/recent_work.py -- do not edit by hand.
Regenerate with `poetry run python scripts/recent_work.py`, or by running
either of the two export scripts, which call it. -->
"""


def _text(raw):
    """Titles carry markup and entities -- `<i>via</i>`, `&amp;`. Both would
    otherwise reach the page as literal characters."""
    return html.unescape(re.sub(r"<[^>]+>", "", str(raw or ""))).strip()


def author_list(authors):
    names = []
    for author in authors:
        given, family = author.get("given"), author.get("family")
        if not family:
            # Consortium entries and the like carry no family name.
            names.append(_text(author.get("full_name")))
        elif given:
            names.append(f"{_text(given)[0]}. {_text(family)}")
        else:
            names.append(_text(family))
    if len(names) > MAX_AUTHORS:
        return ", ".join(names[:KEEP_AUTHORS]) + " et al."
    return ", ".join(names)


def load_recent(path=PAPERS_JSON, n=N_ENTRIES):
    """The newest `n` publications. The export is already newest-first."""
    data = json.loads(Path(path).read_text())
    count = len(data["doi"])
    rows = [{key: data[key][str(i)] for key in data} for i in range(count)]
    kept = [r for r in rows if r.get("journal.kind") not in EXCLUDED_KINDS]
    return kept[:n]


def render(papers):
    esc = html.escape
    lines = [HEADER, "```{=html}", '<ul class="recent-list">']
    for paper in papers:
        venue = _text(paper.get("journal.abbreviation") or paper.get("journal.name"))
        volume = _text(paper.get("journal.volume"))
        meta = [esc(author_list(paper["authors"])), " &middot; ", f"<em>{esc(venue)}</em>"]
        if volume:
            meta.append(f" <b>{esc(volume)}</b>")
        meta.append(f" ({esc(str(paper['year']))})")
        lines += [
            "  <li>",
            f'    <a href="https://doi.org/{esc(paper["doi"])}" target="_blank">'
            f"{esc(_text(paper['title']))}</a>",
            f'    <div class="recent-meta">{"".join(meta)}</div>',
            "  </li>",
        ]
    lines += ["</ul>", "```", ""]
    return "\n".join(lines)


def write_include(path=INCLUDE_FILE, papers_json=PAPERS_JSON, n=N_ENTRIES):
    papers = load_recent(papers_json, n)
    Path(path).write_text(render(papers))
    return papers


def main():
    papers = write_include()
    print(f"wrote {INCLUDE_FILE.name} with {len(papers)} publications:")
    for paper in papers:
        print(f"  {paper['year']}  {_text(paper['title'])[:64]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
